<?php

require_once __DIR__ . '/lib/bootstrap.php';

$page_title = 'MICASA INFO';
$body_class = 'page-about';

include __DIR__ . '/partials/header.php';
?>

<section class="about-layout">
  <article class="paper">
    <p class="spiked-label">C1 / WAS IST MICASA</p>
    <h1>MICASA IST EINE OFFENE PLATTFORM FÜR KREATIVE PROJEKTE.</h1>
    <p>MICASA VERBINDET MODE, FILM, MUSIK, DESIGN UND GESELLSCHAFTLICH RELEVANTE THEMEN. IM ZENTRUM STEHEN NICHT NUR DIE ERGEBNISSE, SONDERN DIE GESCHICHTEN, HALTUNGEN UND KOOPERATIONEN, AUS DENEN SIE ENTSTEHEN.</p>
  </article>
  <article class="paper">
    <p class="spiked-label">STRUKTUR / ARBEITSWEISE</p>
    <p>DAS PROJEKT WIRD VON EINEM KLEINEN KERNTEAM ORGANISIERT. KOLLEKTION, WEBSITE, FILME, KAMPAGNEN UND DESIGNS ENTSTEHEN IN GEMEINSAMER PLANUNG UND MIT EXTERNEN ARTISTS UND PARTNERN.</p>
  </article>
  <article class="paper">
    <p class="spiked-label">LANGFRISTIGE VISION</p>
    <p>MICASA SOLL SICH ZU EINEM NETZWERK AUS KÜNSTLERINNEN, FILMEMACHERINNEN, MUSIKERINNEN UND GESTALTERINNEN ENTWICKELN, DIE AN INTERDISZIPLINÄREN ARBEITEN, KOLLEKTIONEN, FILMEN, MUSIKPRODUKTIONEN UND SOZIALEN PROJEKTEN ARBEITEN.</p>
  </article>
  <article class="paper">
    <p class="spiked-label">WARUM DAS BESONDERS IST</p>
    <p>WIR GLAUBEN AN KUNST, DIE ETWAS AUSLÖST. NICHT NUR KLICKS, SONDERN GEDANKEN. WIR ERZÄHLEN GESCHICHTEN, ABER WIR MACHEN KEINE SHOW. WIR BAUEN KAMPAGNEN, ABER KEINE FASSADE.</p>
  </article>
</section>

<?php include __DIR__ . '/partials/footer.php'; ?>
